# Generated by Django 6.0.2 on 2026-02-17 07:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventCatalog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "notification_event_catalog",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="LkActorType",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "notification_lk_actor_type",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="LkChannel",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "notification_lk_channel",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="LkModule",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "notification_lk_module",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="LkPriority",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("weight", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "notification_lk_priority",
                "ordering": ["-weight", "code"],
            },
        ),
        migrations.CreateModel(
            name="LkStatus",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "notification_lk_status",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="EventRule",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "recipient_policy",
                    models.CharField(default="TEACHER", max_length=64),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "event",
                    models.ForeignKey(
                        db_column="event_code",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rules",
                        to="notification.eventcatalog",
                        to_field="code",
                    ),
                ),
                (
                    "priority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_rules",
                        to="notification.lkpriority",
                    ),
                ),
            ],
            options={
                "db_table": "notification_event_rule",
                "ordering": ["event_id", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InAppMessage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField()),
                ("title", models.TextField(blank=True)),
                ("body", models.TextField()),
                ("event_code", models.CharField(blank=True, max_length=100)),
                ("entity_type", models.TextField(blank=True)),
                ("entity_id", models.TextField(blank=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "notification_in_app_message",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "is_read", "-created_at"],
                        name="notif_inapp_user_unread_idx",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="eventcatalog",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="notification.lkmodule",
            ),
        ),
        migrations.CreateModel(
            name="Outbox",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("recipient_user_id", models.BigIntegerField()),
                ("subject", models.TextField(blank=True)),
                ("body", models.TextField()),
                ("to_phone", models.TextField(blank=True)),
                ("to_email", models.TextField(blank=True)),
                ("entity_type", models.TextField(blank=True)),
                ("entity_id", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("attempt_count", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=5)),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_error", models.TextField(blank=True)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_items",
                        to="notification.lkchannel",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        db_column="event_code",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_items",
                        to="notification.eventcatalog",
                        to_field="code",
                    ),
                ),
                (
                    "priority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_items",
                        to="notification.lkpriority",
                    ),
                ),
                (
                    "recipient_actor_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_items",
                        to="notification.lkactortype",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_items",
                        to="notification.lkstatus",
                    ),
                ),
            ],
            options={
                "db_table": "notification_outbox",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("attempt_no", models.IntegerField()),
                ("provider", models.TextField(blank=True)),
                ("provider_message_id", models.TextField(blank=True)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_logs",
                        to="notification.lkstatus",
                    ),
                ),
                (
                    "outbox",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_logs",
                        to="notification.outbox",
                    ),
                ),
            ],
            options={
                "db_table": "notification_delivery_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("language", models.CharField(default="en", max_length=8)),
                ("subject", models.TextField(blank=True)),
                ("body", models.TextField()),
                ("version", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="templates",
                        to="notification.lkchannel",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        db_column="event_code",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="templates",
                        to="notification.eventcatalog",
                        to_field="code",
                    ),
                ),
            ],
            options={
                "db_table": "notification_template",
                "ordering": ["event_id", "channel_id", "language", "-version"],
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField()),
                ("allow_sms", models.BooleanField(default=True)),
                ("allow_email", models.BooleanField(default=True)),
                ("allow_in_app", models.BooleanField(default=True)),
                ("preferred_lang", models.CharField(default="en", max_length=8)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_preferences",
                        to="notification.lkactortype",
                    ),
                ),
            ],
            options={
                "db_table": "notification_user_preference",
                "ordering": ["user_id", "actor_type_id"],
            },
        ),
        migrations.CreateModel(
            name="EventRuleChannel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "event_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_channels",
                        to="notification.eventrule",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_rule_channels",
                        to="notification.lkchannel",
                    ),
                ),
            ],
            options={
                "db_table": "notification_event_rule_channel",
                "ordering": ["event_rule_id", "channel_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event_rule", "channel"),
                        name="notif_event_rule_channel_unique",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="eventcatalog",
            index=models.Index(
                fields=["module", "is_active"], name="notif_event_mod_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventrule",
            index=models.Index(
                condition=models.Q(("is_active", True)),
                fields=["event"],
                name="notif_event_rule_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outbox",
            index=models.Index(
                fields=["status", "next_attempt_at"], name="notif_outbox_due_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outbox",
            index=models.Index(
                fields=["recipient_user_id", "-created_at"],
                name="notif_outbox_recipient_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deliverylog",
            index=models.Index(
                fields=["outbox", "-created_at"], name="notif_delivery_outbox_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="deliverylog",
            constraint=models.UniqueConstraint(
                fields=("outbox", "attempt_no"), name="notif_delivery_unique_attempt"
            ),
        ),
        migrations.AddIndex(
            model_name="template",
            index=models.Index(
                condition=models.Q(("is_active", True)),
                fields=["event", "channel"],
                name="notif_template_active_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="template",
            constraint=models.UniqueConstraint(
                fields=("event", "channel", "language", "version"),
                name="notif_template_unique_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="userpreference",
            constraint=models.UniqueConstraint(
                fields=("user_id", "actor_type"), name="notif_user_pref_unique_actor"
            ),
        ),
    ]
