# Generated by Codex on 2026-02-17

from django.db import migrations


def seed_notification_data(apps, schema_editor):
    LkModule = apps.get_model("notification", "LkModule")
    LkChannel = apps.get_model("notification", "LkChannel")
    LkStatus = apps.get_model("notification", "LkStatus")
    LkPriority = apps.get_model("notification", "LkPriority")
    LkActorType = apps.get_model("notification", "LkActorType")
    EventCatalog = apps.get_model("notification", "EventCatalog")

    modules = [
        ("REGISTRATION", "Registration"),
        ("LICENCE", "Licence"),
        ("INTERNSHIP", "Internship"),
        ("CPD", "CPD"),
        ("PAYMENT", "Payment"),
        ("UAA", "User Access & Administration"),
        ("NOTIFICATION", "Notification"),
    ]
    for code, name in modules:
        LkModule.objects.update_or_create(
            code=code,
            defaults={"name": name, "is_active": True},
        )

    channels = [
        ("SMS", "SMS"),
        ("EMAIL", "Email"),
        ("IN_APP", "In-App"),
    ]
    for code, name in channels:
        LkChannel.objects.update_or_create(
            code=code,
            defaults={"name": name, "is_active": True},
        )

    statuses = [
        ("QUEUED", "Queued"),
        ("SENT", "Sent"),
        ("DELIVERED", "Delivered"),
        ("FAILED", "Failed"),
        ("CANCELLED", "Cancelled"),
    ]
    for code, name in statuses:
        LkStatus.objects.update_or_create(
            code=code,
            defaults={"name": name, "is_active": True},
        )

    priorities = [
        ("LOW", "Low", 10),
        ("NORMAL", "Normal", 50),
        ("HIGH", "High", 80),
        ("CRITICAL", "Critical", 100),
    ]
    for code, name, weight in priorities:
        LkPriority.objects.update_or_create(
            code=code,
            defaults={"name": name, "weight": weight, "is_active": True},
        )

    actor_types = [
        ("TEACHER", "Teacher"),
        ("STAFF", "Staff"),
        ("SYSTEM", "System"),
    ]
    for code, name in actor_types:
        LkActorType.objects.update_or_create(
            code=code,
            defaults={"name": name, "is_active": True},
        )

    event_specs = [
        ("REGISTRATION_SUBMITTED", "Teacher submitted registration application", "REGISTRATION"),
        ("REGISTRATION_APPROVED", "Registration approved", "REGISTRATION"),
        ("REGISTRATION_REJECTED", "Registration rejected", "REGISTRATION"),
        ("LICENCE_ISSUED", "Licence issued and activated", "LICENCE"),
        ("LICENCE_EXPIRING_SOON", "Licence expiring soon reminder", "LICENCE"),
        ("INTERNSHIP_ASSIGNED", "Internship placement assigned", "INTERNSHIP"),
        ("CPD_NON_COMPLIANT", "Teacher is not compliant with CPD", "CPD"),
        ("PAYMENT_INVOICE_GENERATED", "Invoice generated", "PAYMENT"),
        ("PAYMENT_CONFIRMED", "Payment confirmed/reconciled", "PAYMENT"),
        ("ACCOUNT_ROLE_CHANGED", "User role changed", "UAA"),
    ]
    for code, description, module_code in event_specs:
        module = LkModule.objects.get(code=module_code)
        EventCatalog.objects.update_or_create(
            code=code,
            defaults={
                "description": description,
                "module_id": module.id,
                "is_active": True,
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_notification_data, noop_reverse),
    ]
