# Generated by Django 6.0.2 on 2026-02-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="request_body_example",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="channel",
            name="request_body_schema",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="channel",
            name="request_content_type",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="channel",
            name="requires_request_body",
            field=models.BooleanField(default=False),
        ),
    ]
