# Generated by Django 6.0.2 on 2026-02-16 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediator", "0002_channel_request_body_example_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalSystemRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization", models.CharField(max_length=160)),
                ("api_code", models.CharField(blank=True, max_length=120, null=True)),
                ("push_code", models.CharField(blank=True, max_length=120, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_system_registrations",
                        to="mediator.channel",
                    ),
                ),
            ],
            options={
                "ordering": ["organization", "channel__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("channel", "organization"),
                        name="uniq_registration_channel_organization",
                    )
                ],
            },
        ),
    ]
