# Generated by Django 6.0.2 on 2026-02-16 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediator", "0003_externalsystemregistration"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="externalsystemregistration",
            name="uniq_registration_channel_organization",
        ),
        migrations.AlterField(
            model_name="externalsystemregistration",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_system_registrations",
                to="mediator.channel",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalsystemregistration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("channel__isnull", False)),
                fields=("channel", "organization"),
                name="uniq_registration_channel_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalsystemregistration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("channel__isnull", True)),
                fields=("organization",),
                name="uniq_registration_org_global",
            ),
        ),
    ]
